In [20]:
#please import Project01_data.mat inside cwd first!
import numpy as np
from mat4py import loadmat
M = loadmat('Project01_data.mat')
A = M['A']
B = M['B']
print("A=")
print(A)
print("B=")
print(B)

A=
[[0.4976, -16.0, -9.0, 10.0, 16.0, -2.0], [0.058, -11.0, 16.0, 0.0, 13.0, 17.0], [0.9783, 4.0, 1.0, 10.0, -11.0, 10.0], [0.0246, 11.0, 3.0, -16.0, 17.0, -6.0], [0.1509, -13.0, -19.0, 1.0, -2.0, 1.0], [0.6284, -15.0, -15.0, -1.0, -3.0, 9.0]]
B=
[[-16.0, -9.0, 10.0, 16.0, -2.0, 0.1066], [-11.0, 16.0, 0.0, 13.0, 17.0, 0.4511], [4.0, 1.0, 10.0, -11.0, 10.0, 0.1943], [11.0, 3.0, -16.0, 17.0, -6.0, 0.8257], [-13.0, -19.0, 1.0, -2.0, 1.0, 0.1856], [-15.0, -15.0, -1.0, -3.0, 9.0, 0.0642]]


In [23]:
import numpy as np
from mat4py import loadmat
M = loadmat('Project01_data.mat')
A = M['A']
B = M['B']
a = np.array(A)
b = np.array(B)
print("AXB=")
print(a.dot(b))

AXB=
[[  64.0384     -513.4784     -227.024        42.9616     -424.9952
     2.18494416]
 [-239.928      -662.522       156.58       -395.072       138.884
     1.6570828 ]
 [  47.3472      145.1953     -161.217       218.6528       95.0434
     8.96038678]
 [-416.3936     -102.2214      309.246      -177.6064      275.9508
    -4.89357764]
 [  86.5856     -202.3581     -207.491        60.4144     -410.3018
    -9.02121406]
 [ -12.0544     -341.6556     -139.716       -57.9456     -322.2568
   -10.41871256]]


In [13]:
import numpy as np
from mat4py import loadmat
M = loadmat('Project01_data.mat')
Z = M['Z']
z = np.array(Z)
n = len(z)
for i in range(n):
    if z[i,i]==0:#check first since pivot should not be zero
        for k in range(n):
            if z[k,i]!=0:
                for j in range(n):
                    z[i,j],z[k,j]=z[k,j],z[i,j]
                    #Use multiple assignment to swap the element at each index in the array.
                break  #pivot is now valid
    pivot = z[i,i]
    for j in range(i,n+1):
        z[i,j] /= pivot#each element on the same row is divided by the pivot
    for k in range(n):
        if z[k,i]==0 or k==i:
            continue
        quo = z[k,i]
        for j in range(i,n+1):
            z[k,j]-=quo * z[i,j]
print(z)            
    
    
                


[[ 1  0  0  0  0  0  0  0  0  0  0]
 [ 0  1  0  0  0  0  0  0  0  0 -3]
 [ 0  0  1  0  0  0  0  0  0  0 12]
 [ 0  0  0  1  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  0  0  0  0  0  2]
 [ 0  0  0  0  0  1  0  0  0  0 -2]
 [ 0  0  0  0  0  0  1  0  0  0 -5]
 [ 0  0  0  0  0  0  0  1  0  0 -1]
 [ 0  0  0  0  0  0  0  0  1  0  1]
 [ 0  0  0  0  0  0  0  0  0  1  2]]
