In [102]:
import numpy as np
n,a = map(int, input().split())
z = np.zeros((n,n))
ii = np.zeros((n,n))
for i in range(n):#input matrix
    row = input().split()
    for j in range(a):
        z[i,j] = row[j]
for i in range(n):#create a indentity matrix
    ii[i,i] = 1
# input matrix
for i in range(n):
    if z[i,i]==0:#check first since pivot should not be zero
        for k in range(i+1,n):
            if z[k,i]!=0:
                for j in range(n):
                    z[i,j],z[k,j]=z[k,j],z[i,j]
                    ii[i,j],ii[k,j]=ii[k,j],ii[i,j]
                    
                    
                    #Use multiple assignment to swap the element at each index in the array.
                break  #pivot is now valid
    pivot = z[i,i]
    for j in range(n):
        z[i,j] /= pivot#each element on the same row is divided by the pivot, 
                    #which made sure that pivots are all 1
        ii[i,j] /= pivot
 
    for k in range(n):
        if z[k,i]==0 or k==i:
            continue
        quo = z[k,i]
        for j in range(n):
            z[k,j]-=quo * z[i,j]
            ii[k,j]-=quo * ii[i,j]
print(ii)

3 3
1 -1 -2
2 -3 -5
-1 3 5
[[ 0.  1.  1.]
 [ 5. -3. -1.]
 [-3.  2.  1.]]
