In [9]:
###################### STEP 1 ######################
#functions importing
import numpy as np
from numpy import linalg
#matrix initializing
arr = np.array([[1,1,1,1],[2,1,-1,-2],[1,-1,-1,1],[1,-2,2,-1]])
#a stands for the eigenvalues of the given matrix, while
#b stands for the corresponding eigenvectors of eigenvalues.
#note that these vectors are presented columnwise.
a, p = np.linalg.eig(arr)
#do a matrix tranposition so that we can access the eigenvectors more easily. 
c = p.transpose()
print("λ1 = ",a[0],", v1 = ",c[0])
print("λ2 = ",a[1],", v2 = ",c[1])
print("λ3 = ",a[2],", v3 = ",c[2])
print("λ4 = ",a[3],", v4 = ",c[3])
print("\n")
print("p = \n",p)
#b and c both represent matrices that consist of eigenvectors.
#the former is columnwise, yet the later is rowwise.

λ1 =  2.828427124746191 , v1 =  [-0.15622986  0.68963195 -0.37717224 -0.59811462]
λ2 =  2.2360679774997902 , v2 =  [ 0.69455348 -0.13264791  0.42925766  0.56190557]
λ3 =  -2.8284271247461925 , v3 =  [-0.37717224  0.59811462  0.15622986  0.68963195]
λ4 =  -2.2360679774997885 , v4 =  [ 0.42925766 -0.56190557 -0.69455348 -0.13264791]


p = 
 [[-0.15622986  0.69455348 -0.37717224  0.42925766]
 [ 0.68963195 -0.13264791  0.59811462 -0.56190557]
 [-0.37717224  0.42925766  0.15622986 -0.69455348]
 [-0.59811462  0.56190557  0.68963195 -0.13264791]]


In [10]:
###################### STEP 2 ######################
import numpy as np
from numpy import linalg
arr = np.array([[1,1,1,1],[2,1,-1,-2],[1,-1,-1,1],[1,-2,2,-1]])
a,p = np.linalg.eig(arr)
#we are using the eigenvector matrix, which is p.
arr = p
#note that the inversing method below are extracted from Project 2.
#create an identity matrix using for loop.
iden = np.zeros((4,4))
for i in range(4):
    iden[i,i] = 1
for i in range(4):
    #check first since pivot should not be zero.
    if arr[i,i]==0:
        for k in range(i+1,4):
            if arr[k,i]!=0:
                #Use multiple assignment to swap the element at each index in the array.
                for j in range(4):
                    arr[i,j],arr[k,j]=arr[k,j],arr[i,j]
                    iden[i,j],iden[k,j]=iden[k,j],iden[i,j]
                break  
                #pivot is now valid
    pivot = arr[i,i]
    for j in range(4):
        arr[i,j] /= pivot
        #each element on the same row is divided by the pivot, 
        #which made sure that pivots are all 1.
        iden[i,j] /= pivot
    #calculations below are based on elimination method    
    for k in range(4):
        if arr[k,i]==0 or k==i:
            continue
        quo = arr[k,i]
        for j in range(4):
            arr[k,j]-=quo * arr[i,j]
            iden[k,j]-=quo * iden[i,j]
#the identity matrix has altered into the inverse of eigenvector matrix, by the inversing algorithm.            
print("p^(-1) = \n",iden)

p^(-1) = 
 [[ 0.75434448  1.06680419 -0.31245971 -0.44188477]
 [ 1.25645904  0.56190557  0.29660975  0.13264791]
 [-0.31245971  0.44188477 -0.75434448  1.06680419]
 [ 0.29660975 -0.13264791 -1.25645904  0.56190557]]


In [11]:
###################### STEP 3 ######################
###################### START of step 2, the inversing method ######################
import numpy as np
from numpy import linalg
A = np.array([[1,1,1,1],[2,1,-1,-2],[1,-1,-1,1],[1,-2,2,-1]])
x,p = np.linalg.eig(A)
arr = p
iden = np.zeros((4,4))

for i in range(4):
    iden[i,i] = 1
for i in range(4):
    if arr[i,i]==0:
        for k in range(i+1,4):
            if arr[k,i]!=0:
                for j in range(4):
                    arr[i,j],arr[k,j]=arr[k,j],arr[i,j]
                    iden[i,j],iden[k,j]=iden[k,j],iden[i,j]
                break  
    pivot = arr[i,i]
    for j in range(4):
        arr[i,j] /= pivot
        iden[i,j] /= pivot   
    for k in range(4):
        if arr[k,i]==0 or k==i:
            continue
        quo = arr[k,i]
        for j in range(4):
            arr[k,j]-=quo * arr[i,j]
            iden[k,j]-=quo * iden[i,j]
###################### END of step 2, the inversing method ######################
#change name to arc-p for better recognition.
arcp = iden
x,p = np.linalg.eig(A)
#dot product
D = np.dot(arcp,A)
D = np.dot(D,p)
#round into the 5th number after decimal.
D = np.round(D,5)
print("D = \n",D)

D = 
 [[ 2.82843 -0.      -0.       0.     ]
 [ 0.       2.23607 -0.      -0.     ]
 [-0.       0.      -2.82843 -0.     ]
 [-0.       0.       0.      -2.23607]]


In [12]:
###################### STEP 4 ######################
###################### START of step 3 ######################
import numpy as np
from numpy import linalg
A = np.array([[1,1,1,1],[2,1,-1,-2],[1,-1,-1,1],[1,-2,2,-1]])
x,p = np.linalg.eig(A)
arr = p
iden = np.zeros((4,4))

for i in range(4):
    iden[i,i] = 1
for i in range(4):
    if arr[i,i]==0:
        for k in range(i+1,4):
            if arr[k,i]!=0:
                for j in range(4):
                    arr[i,j],arr[k,j]=arr[k,j],arr[i,j]
                    iden[i,j],iden[k,j]=iden[k,j],iden[i,j]
                break  
    pivot = arr[i,i]
    for j in range(4):
        arr[i,j] /= pivot
        iden[i,j] /= pivot   
    for k in range(4):
        if arr[k,i]==0 or k==i:
            continue
        quo = arr[k,i]
        for j in range(4):
            arr[k,j]-=quo * arr[i,j]
            iden[k,j]-=quo * iden[i,j]
arcp = iden
x,p = np.linalg.eig(A)
D = np.dot(arcp,A)
D = np.dot(D,p)
D = np.round(D,5)
###################### END of step 3 ######################
#define a function that does matrix dot product
#note that this is NOT from NumPy
def dot_product(left,right):
    result = np.zeros((4,4))
    for i in range(4):
        for j in range(4):
            for k in range(4):
                result[i,j] += left[i,k] * right[k,j]
    return result
#seperate into few steps
# p * D
ans = dot_product(p,D)
#(p * D) * D^99
for i in range(99):
    ans = dot_product(ans,D)
#[(p * D) * D^99] * arcp  
ans = dot_product(ans,arcp)
print("A^100 = \n",ans)

A^100 = 
 [[ 8.88262633e+34 -4.75797596e+44  4.75797596e+44 -4.75797596e+44]
 [ 4.75797596e+44  1.42739279e+45 -9.51595192e+44  4.75797596e+44]
 [-4.75797596e+44 -4.75797596e+44  8.88277723e+34  4.75797596e+44]
 [-9.51595192e+44 -4.75797596e+44 -4.75797596e+44  1.42739279e+45]]
